spring.application.name=EmployeeCrudOperation

server.port=8090

spring.datasource.name=tushar_practice
spring.datasource.url=jdbc:mysql://localhost:3306/tushar_practice
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hinermtae.dialect=org.hibernate.dialect.MySQL55Dialect
spring.jpa.hibernate.ddl-auto=update
