

  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/powercard
      username: postgres
      password: admin
      driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          default_schema: practice
      database-platform: org.hibernate.dialect.PostgreSQLDialect

